Freelancers.Crowd.MVC/Controllers/BaseController.cs
using Freelancers.Crowd.Domain.Entities;
using Freelancers.Crowd.Domain.Interfaces.Repositories;
using Freelancers.Crowd.Domain.Services;
using Freelancers.Crowd.Domain.Entities.Enum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Freelancers.Crowd.MVC.Controllers
{
    public class BaseController : Controller
    {

        private readonly ServiceBase<Briefing> _serviceBriefing;
        private readonly ServiceUser _serviceUser;

        public BaseController(ServiceBase<Briefing> serviceBriefing, ServiceUser serviceUser)
        {
            _serviceBriefing = serviceBriefing;
            _serviceUser = serviceUser;
        }

        [HttpGet]
        public ActionResult Menu()
        {
            if (HttpContext.Request.Cookies["role"] == null)
            {
                RedirectToAction("Logout", "Login");
            }
            
            IEnumerable<Briefing> briefings = null;

            var email = HttpContext.User.Identity.Name;
            var user = _serviceUser.GetById(x => x.Email.Equals(email));


            var role = new HttpCookie("role", Enum.GetName(typeof(RoleType), user.Role));
            role.Expires = DateTime.Now.AddMinutes(525600);
            role.Expires = DateTime.Now.AddDays(1);
            Response.Cookies.Add(role);

            if (user.Role == RoleType.MASTER || user.Role == RoleType.EMPLOYEE || user.Role == RoleType.CLIENT)
                briefings = _serviceBriefing.GetAll().OrderBy(x => x.CreatedAt).ToList();
            else if (user.Role == RoleType.FREELANCER)
                briefings = _serviceBriefing.GetAll(x => x.Freelancers.Any(y => y.Id == user.Freelancers.Id)).OrderBy(x => x.CreatedAt).ToList();

            var countBadge = briefings.Sum(x => x.Messages.Where(y => y.User != null && y.Read == false && y.FreelancerId == user.IdFreelancer).GroupBy(y => y.FreelancerId).Select(y => y.First()).ToList().Count);
            ViewBag.CountBriefing = countBadge;
            return PartialView("_MenuBar");
        }
    }
}

Freelancers.Crowd.MVC/Controllers/CustomerController.cs
using Freelancers.Crowd.Domain.Entities;
using Freelancers.Crowd.Domain.Interfaces.Repositories;
using Freelancers.Crowd.Domain.Services;
using ImageResizer;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Freelancers.Crowd.MVC.Controllers
{
    [Authorize(Roles = "MASTER")]
    [SessionState(System.Web.SessionState.SessionStateBehavior.ReadOnly)]
    public class CustomerController : Controller
    {
        private readonly ServiceBase<Customer> _serviceCustomer;
        private readonly ServiceBase<State> _serviceState;
        private readonly ServiceBase<City> _serviceCity;

        public CustomerController(ServiceBase<Customer> serviceCustomer, ServiceBase<State> serviceState, ServiceBase<City> serviceCity)
        {
            _serviceCustomer = serviceCustomer;
            _serviceState = serviceState;
            _serviceCity = serviceCity;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var customers = _serviceCustomer.GetAll().Where(x => x.Active == true);
            return View(customers);
        }


        [HttpGet]
        public ActionResult Edit(int idCustomer)
        {
            var customer = _serviceCustomer.GetById(idCustomer);
            ViewBag.States = _serviceState.GetAll();
            ViewBag.Cities = _serviceCity.GetAll();

            return View(customer);
        }

        [HttpPost]
        public ActionResult Edit(Customer customer, HttpPostedFileBase Logo)
        {
            string path = Server.MapPath("~/Content/images/customer/");
            if (Logo != null && Logo.ContentLength > 0)
            {
                string ext = Path.GetExtension(Logo.FileName);
                path += customer.Name.Replace(" ", "") + "_" + customer.Id + ext;
                Logo.SaveAs(path);
                customer.Logo = "/Content/images/customer/" + customer.Name.Replace(" ", "") + "_" + customer.Id + ext;

                //Crops to a square (in place)
                ImageBuilder.Current.Build(path, path,
                                           new ResizeSettings("width=80"));

            }

            _serviceCustomer.Update(customer);


            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Inactive(int idCustomer)
        {
            var customer = _serviceCustomer.GetById(idCustomer);

            customer.Active = false;
            _serviceCustomer.Update(customer);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.States = _serviceState.GetAll();
            ViewBag.Cities = _serviceCity.GetAll();

            return View();
        }

        [HttpPost]
        public ActionResult Add(Customer customer, HttpPostedFileBase Logo)
        {
            string path = Server.MapPath("~/Content/images/customer/");
            if (Logo != null && Logo.ContentLength > 0)
            {
                string ext = Path.GetExtension(Logo.FileName);
                path += customer.Name.Replace(" ", "") + "_" + customer.Id + ext;
                Logo.SaveAs(path);
                customer.Logo = "/Content/images/customer/" + customer.Name.Replace(" ", "") + "_" + customer.Id + ext;
                
                //Crops to a square (in place)
                ImageBuilder.Current.Build(path, path,
                                           new ResizeSettings("width=80"));

            }


            _serviceCustomer.Add(customer);
            return RedirectToAction("Index");
        }
    }
}

Freelancers.Crowd.MVC/Controllers/LoginController.cs
using Freelancers.Crowd.Domain.Entities;
using Freelancers.Crowd.Domain.Entities.Enum;
using Freelancers.Crowd.Domain.Interfaces.Repositories;
using Freelancers.Crowd.Domain.Services;
using Freelancers.Crowd.MVC.Models.Network.Mandrill;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Freelancers.Crowd.MVC.Controllers
{
    public class LoginController : Controller
    {

        private readonly ServiceUser _serviceUser;
        private readonly ServiceFreelancer _serviceFreelancer;

        public LoginController(ServiceUser serviceUser, ServiceFreelancer serviceFreelancer)
        {
            _serviceUser = serviceUser;
            _serviceFreelancer = serviceFreelancer;
        }

        

        
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var email = HttpContext.User.Identity.Name;
                var user = _serviceUser.GetById(x => x.Email.Equals(email));

                var role = new HttpCookie("role", Enum.GetName(typeof(RoleType), user.Role));
                role.Expires = DateTime.Now.AddMinutes(525600);
                role.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Add(role);

                if (user.Role == RoleType.MASTER)
                {                    
                    return RedirectToAction("Index", "Profissional");
                }
                else if (user.Role == RoleType.FREELANCER)
                {
                    return RedirectToAction("Briefing", "Project");
                }
            }
            if (TempData["Status"] != null)
                ViewBag.Status = TempData["Status"];

           /* if (Request.Url.Host.Contains(ConfigurationManager.AppSettings["url:freelancer"]))
            {*/
                TempData["Status"] = TempData["Status"];
                return RedirectToAction("Index", "SingIn");
            //}
            /*else
            {
                if (TempData["Error"] != null)
                    ViewBag.Error = true;
            }*/


            //return View();
        }


        //This method is just used after register 
        [HttpGet]
        public ActionResult Login()
        {
            String email = TempData["email"].ToString(); 
            String password = TempData["password"].ToString();
            return Index(email, password);
        }

  

        [HttpPost]
        public ActionResult Index(String email, String password)
        {
            
            var user = _serviceUser.GetById(x => x.Email == email);

            if (user != null)
            {
                if (!string.IsNullOrEmpty(email) && !string.IsNullOrEmpty(password))
                {
                    user = _serviceUser.Authentication(email, password);
                    if (user != null && user.Id > 0)
                    {
                        var imgUser = new HttpCookie("img_user", user.Photo);
                        imgUser.Expires = DateTime.Now.AddMinutes(525600);
                        Response.Cookies.Add(imgUser);

                        FormsAuthentication.SetAuthCookie(user.Email, true);
                        var role = new HttpCookie("role", Enum.GetName(typeof(RoleType), user.Role));
                        role.Expires = DateTime.Now.AddMinutes(525600);
                        role.Expires = DateTime.Now.AddDays(1);
                        Response.Cookies.Add(role);

                        if (user.Role == RoleType.MASTER || user.Role == RoleType.EMPLOYEE || user.Role == RoleType.CLIENT)
                        {
                            return RedirectToAction("Index", "Profissional");
                        }
                        else if (user.Role == RoleType.FREELANCER)
                        {
                            return RedirectToAction("Briefing", "Project");
                        }
                    }
                    else
                    {
                        ViewBag.Error = true;
                        TempData["Error"] = ViewBag.Error;
                        TempData["StatusUser"] = "pass";


                        //if (Request.Url.Host.Contains(ConfigurationManager.AppSettings["url:freelancer"]))
                        return RedirectToAction("Index", "SingIn", new { email = email });
                        //else
                            //return RedirectToAction("Index", "Login");
                                                
                    }
                }
                else
                {
                    TempData["StatusUser"] = "pass";
                    return RedirectToAction("Index", "SingIn", new { email = email });
                }
                
            }
            else
            {
                var freelancer = _serviceFreelancer.GetById(x => x.Email == email);

                if (freelancer != null)
                {
                    TempData["StatusUser"] = "newUser";
                    return RedirectToAction("Index", "SingIn", new { email = email });
                }
                else
                {
                    TempData["StatusUser"] = "register";
                    return RedirectToAction("Index", "SingIn", new { email = email });
                }
            }
            

            /*
            ViewBag.Error = true;
            if (Request.Url.Host.Contains(ConfigurationManager.AppSettings["url:freelancer"]))
            {
                TempData["Error"] = ViewBag.Error;
                return RedirectToAction("Index", "SingIn");
            }*/
            return View("Index");
        }

        public ActionResult ForgetPassword()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult ForgetPassword(String email)
        {
            var guid = _serviceUser.RecoverPassword(email);
            if (guid != null)
            {
                var freelancer = _serviceUser.GetById(p => p.Email.Equals(email), "Freelancers");
                new Thread(() => {
                    var variables = new Dictionary<string, string> { { "EMAIL", email }, { "ID", guid.ToString() } };
                    Email sendEmail = new Email();
                    sendEmail.Send(freelancer.Email, freelancer.Name, "CROWD - Recuperação de Senha", "change-password", variables);
                }).Start();
                ViewBag.Status = "sucesso";
            }
            else
            {
                ViewBag.Status = "error";
            }
            //if (Request.Url.Host.Contains(ConfigurationManager.AppSettings["url:freelancer"]))
            //{
                TempData["StatusForget"] = ViewBag.Status;
                return RedirectToAction("Index", "SingIn");
            //}
            //return View();
        }


        public ActionResult RecoverPassword(string email, string hash)
        {
            if (Request.Url.Host.Contains(ConfigurationManager.AppSettings["url:freelancer"]))
                return RedirectToAction("RecoverPassword", "SingIn", new { email = email, hash = hash });
            ViewBag.Email = email;
            ViewBag.Hash = hash;
            return View();
        }

        [HttpPost]
        public ActionResult RecoverPassword(string email, string hash, string password)
        {
            var change = _serviceUser.ChangePassword(email, password, hash);
            if (change)
                //Alterado com sucesso
                return Index(email, password);
            else
            {
                TempData["StatusRecovery"] = "error";
                //if (Request.Url.Host.Contains(ConfigurationManager.AppSettings["url:freelancer"]))
                return RedirectToAction("Index", "SingIn");
            }
            //Não foi possivel alterar sua senha
            //return View();
        }
        
        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult NewUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewUser(string email, string password)
        {
            var freelancer = _serviceFreelancer.GetById(x => x.Email.Equals(email));
            if (freelancer != null && freelancer.Id > 0)
            {
                var user = _serviceUser.GetById(x => x.IdFreelancer == freelancer.Id);

                if (freelancer != null && freelancer.Id > 0 && user != null && user.Id > 0)
                {
                    _serviceUser.Add(new User
                    {
                        Name = freelancer.Name,
                        Email = email,
                        Password = password,
                        IdFreelancer = freelancer.Id,
                        Role = Domain.Entities.Enum.RoleType.FREELANCER
                    });

                    TempData["Status"] = "sucesso-new";
                    return Index(email, password);
                }
                else
                {
                    TempData["Status"] = "error-freela";
                }
            }
            else
            {
                TempData["Status"] = "error-freela";
            }
            //if (Request.Url.Host.Contains(ConfigurationManager.AppSettings["url:freelancer"]))
            //{
                TempData["StatusNewUser"] = TempData["Status"];
                return RedirectToAction("Index", "SingIn");
            //}
            //return RedirectToAction("Index");
        }
    }

}

Freelancers.Crowd.MVC/Views/Base/_MenuBar.cshtml
@{
    Layout = null;
    var role = HttpContext.Current.Request.Cookies["role"];

    var photo = HttpContext.Current.Request.Cookies["img_user"];
}
<div class="site-menubar">
    <div class="site-menubar-body">
        <div>
            <div>
                <ul class="site-menu">
                    
                    @if (role.Value.Equals("MASTER"))
                    {
                        <li class="site-menu-item" data-name="User">
                            <a href="@Url.Action("Index", "Customer")">
                                <i class="icon fa-user" aria-hidden="true"></i>&nbsp;
                                <span class="site-menu-title hideInMobile">Clientes</span>
                            </a>
                        </li>
                        <li class="site-menu-item" data-name="Profissionais">
                            <a href="@Url.Action("Index", "Profissional")">
                                <i class="icon fa-users" aria-hidden="true"></i>&nbsp;
                                <span class="site-menu-title hideInMobile">Profissionais</span>
                            </a>
                        </li>
                    }
                    else if (role.Value.Equals("GERENTE"))
                    {
                        <li class="site-menu-item" data-name="User">
                            <a href="@Url.Action("Index", "User")">
                                <i class="icon fa-user" aria-hidden="true"></i>&nbsp;
                                <span class="site-menu-title hideInMobile">Usuários</span>
                            </a>
                        </li>

                        <li class="site-menu-item" data-name="Profissionais">
                            <a href="@Url.Action("Index", "Profissional")">
                                <i class="icon fa-users" aria-hidden="true"></i>&nbsp;
                                <span class="site-menu-title hideInMobile">Profissionais</span>
                            </a>
                        </li>
                    }
                    else if (role.Value.Equals("ADMIN"))
                    {
                        <li class="site-menu-item" data-name="Profissionais">
                            <a href="@Url.Action("Index", "Profissional")">
                                <i class="icon fa-users" aria-hidden="true"></i>&nbsp;
                                <span class="site-menu-title hideInMobile">Profissionais</span>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="site-menu-item" data-name="Perfil">
                            <a href="javascript: $('#meuPerfil').click();void(0);" role="menuitem" class="open-slide">
                            <i class="icon fa-user" aria-hidden="true"></i>&nbsp;
                            <span class="hideInMobile">&nbsp;Meu Perfil</span></a>
                        </li>
                    }
                    <li class="site-menu-item" data-name="Briefings">
                        <a href="@Url.Action("Briefing","Project")">
                            <i class="icon fa-paper-plane" aria-hidden="true"></i>&nbsp;
                            <span class="site-menu-title hideInMobile">Briefings&nbsp;</span>
                            @if (ViewBag.CountBriefing > 0)
                            {
                                <span class="badge badge-primary">@ViewBag.CountBriefing</span>
                            }
                        </a> 
                    </li>
                </ul>
            </div>

            <div class="col-md-12 col-xs-12 sidebar-profile">
                <div class="col-md-6  col-xs-12  col-sm-12" data-url="@Url.Action("Edit","User")">
                    <a class="open-slide" href="#">
                        <span class="avatar avatar-online">
                            <img src="@(photo != null && !String.IsNullOrEmpty(photo.Value) ? Url.Content("~/"+photo.Value) : @Url.Content("~/Content/images/default-user-image.png"))" style="min-width: 30px;max-width: 30px;height: 30px;max-height: 30px;" />
                            <i></i>
                        </span>
                    </a>

                    <p data-url="@Url.Action("Edit","User")">
                        <a href="#" role="menuitem" class="open-slide" id="meuPerfil">Meu Perfil</a>
                    </p>
                </div>
                <div class="col-md-6 col-sm-12 col-xs-12 sidebar-profile-logout">
                    <a href="@Url.Action("Logout", "Login")" title="Log out" style="text-decoration:underline;">Log out</a>
                </div>
            </div>

            
            

            
        </div>


       

        
    </div>
</div>